hud_django_v1.0/template_django/DjangoHUD/urls.py
from django.contrib import admin
from django.urls import include, path
from django.conf.urls.static import static
from django.conf import settings

urlpatterns = [
    path('', include('DjangoHUDApp.urls')),
    path('admin/', admin.site.urls),
] 

handler404 = 'DjangoHUDApp.views.handler404'

if settings.DEBUG:
    urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)
else:
    urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

hud_django_v1.0/template_django/DjangoHUDApp/urls.py
from django.urls import path
from . import views

app_name = 'DjangoHUDApp'
urlpatterns = [
    # in use
    
    #general pages
    path('', views.pageLogin, name='pageLogin'),
    path('index', views.index, name='index'),
    path('404/', views.error404, name='error404'),
    path('page/error', views.pageError, name='pageError'),  
    path('logout/', views.logout_view, name='logout'),

    #product pages
    path('all-products', views.pageProduct, name='pageProduct'),
    path('add-product', views.add_product, name='add_product'),
    path('product-details/<int:product_id>/', views.product_details, name='pageProductDetails'),
    path('delete-product/<int:product_id>/', views.delete_product, name='delete_product'),

    #order pages
    path('add-shipment', views.add_shipment, name='add_shipment'),
    path('order', views.pageOrder, name='pageOrder'),
    path('order-details/<int:shipment_id>/', views.pageOrderDetails, name='pageOrderDetails'),
    path('order-details/<int:shipment_id>/print/', views.order_print, name='order_print'),
    path('delete-shipment/<int:shipment_id>/', views.delete_shipment, name='delete_shipment'),
    
    #warehouse pages
    path('warehouse', views.pageWarehouse, name='pageWarehouse'),
    path('stock-per-warehouse/<str:warehouse_name>/', views.stockPerWarehouse, name='pageStockPerWarehouse'),

    #stock pages
    path('stock', views.pageDataManagement, name='pageDataManagement'),

    #recipient pages
    path('recipient', views.pageRecipient, name='pageRecipient'),

    # not in use
    path('analytics/', views.analytics, name='  '),
    path('chart/js/', views.chartJs, name='chartJs'),
    path('chart/apex/', views.chartApex, name='chartApex'),
]

handler404 = 'DjangoHUDApp.views.handler404'

hud_django_v1.0/template_django/DjangoHUDApp/models.py
from django.db import models
from django.contrib.auth.models import User, Group
from django.utils import timezone
from django.conf import settings
from django.db.models import Sum, Max, F
from django.core.exceptions import ValidationError
from django.db import models, transaction
from django.contrib import admin
from django.db.models.signals import post_save, post_delete
from django.dispatch import receiver
import os 

class Recipient(models.Model):
    commanding_unit = models.CharField(max_length=100, db_index=True)  # Added index
    recipient_unit = models.CharField(max_length=100, default='None Specified', db_index=True)  # Added index
    notes = models.CharField(max_length=450, null=True, blank=True)

    def __str__(self):
        return self.commanding_unit
    
    def last_shipment_date(self):
        last_shipment = self.shipmentitem_set.aggregate(last_date=Max('shipment__date'))
        return last_shipment['last_date']
    

class ProductCategory(models.Model):
    name = models.CharField(max_length=100, unique=True)

    def __str__(self):
        return self.name

class ProductUsage(models.Model):
    name = models.CharField(max_length=100, unique=True)

    def __str__(self):
        return self.name

def validate_image(file):
    file_size = file.size
    limit_kb = 10000
    if file_size > limit_kb * 1024:
        raise ValidationError("Max size of file is %s KB" % limit_kb)

    if not file.name.endswith(('.jpg', '.png')):
        raise ValidationError("Μόνο αρχεία .jpg & .png επιτρέπονται")

class Product(models.Model):

    MEASUREMENT_TYPES = (
        ("ΤΕΜΑΧΙΑ", "ΤΕΜΑΧΙΑ"), 
        ("ΜΕΤΡΑ", "ΜΕΤΡΑ"),
        ("ΚΑΜΙΑ ΕΠΙΛΟΓΗ", "ΚΑΜΙΑ ΕΠΙΛΟΓΗ"),       
    )

    name = models.CharField(max_length=100, null=False, db_index=True)  # Added index
    batch_number = models.CharField(max_length=100, null=False, default='KAMIA EPILOGH', blank=True, db_index=True)  # Added index
    unit_of_measurement = models.CharField(max_length=30, choices=MEASUREMENT_TYPES, default='ΚΑΜΙΑ ΕΠΙΛΟΓΗ')
    image = models.ImageField(upload_to='product_images/', validators=[validate_image], blank=True, null=True)
    category = models.ForeignKey(ProductCategory, on_delete=models.SET_NULL, null=True, blank=True, db_index=True)  # Added index
    usage = models.ForeignKey(ProductUsage, on_delete=models.SET_NULL, null=True, blank=True, db_index=True)  # Added index
    description = models.CharField(max_length=200, null=True, blank=True)
    owners = models.ManyToManyField(Group, blank=True, verbose_name='Product Owners')

    def total_stock(self):
        """Return the total stock across all warehouses for this product."""
        return self.stocks.aggregate(total=Sum('quantity'))['total'] or 0

    def __str__(self):
        return f"{self.name} - {self.category}"

@receiver(post_delete, sender=Product)
def delete_product_images(sender, instance, **kwargs):
    if instance.image:
        if os.path.isfile(instance.image.path):
            os.remove(instance.image.path)
            
def validate_shipment_attachment(file):
    file_size = file.size
    limit_kb = 10000
    if file_size > limit_kb * 1024:
        raise ValidationError("Max size of file is %s KB" % limit_kb)

    if not file.name.endswith(('.pdf')):
        raise ValidationError("Μόνο αρχεία pdf")

class Shipment(models.Model):
    SHIPMENT_TYPE_CHOICES = [
        ('IN', 'Εισερχόμενη'),
        ('OUT', 'Εξερχόμενη'),
    ]

    SHIPMENT_METHOD_CHOICES = [
        ('ΥΕΣΑ', 'ΥΕΣΑ'),
        ('ΚΡΥΠΤΟΔΙΑΥΛΟΣ', 'ΚΡΥΠΤΟΔΙΑΥΛΟΣ'),
        ('ΠΑΡΑΛΑΒΗ ΑΠΟ ΕΞΟΥΣΙΟΔΟΤΗΜΕΝΟ ΠΡΟΣΩΠΙΚΟ', 'ΠΑΡΑΛΑΒΗ ΑΠΟ ΕΞΟΥΣΙΟΔΟΤΗΜΕΝΟ ΠΡΟΣΩΠΟ'),
    ]

    user = models.ForeignKey(settings.AUTH_USER_MODEL, on_delete=models.CASCADE, related_name='shipments', db_index=True)  # Added index
    shipment_type = models.CharField(max_length=3, choices=SHIPMENT_TYPE_CHOICES, db_index=True)  # Added index
    date = models.DateTimeField(default=timezone.now, db_index=True)  # Added index
    recipient = models.ForeignKey(Recipient, on_delete=models.CASCADE, db_index=True)  # Added index
    notes = models.CharField(max_length=200, null=True, blank=True)
    attachment = models.FileField(upload_to='shipment_attachments/', validators=[validate_shipment_attachment], null=True, blank=True)
    order_number = models.CharField(max_length=100, null=True, blank=True)
    signatory = models.CharField(max_length=100, null=True, blank=True)

    def save(self, *args, **kwargs):
        if self.notes is None:
            self.notes = ''
        super().save(*args, **kwargs)

    def __str__(self):
        return f" Αποστολή από {self.user} / Τύπου: {self.shipment_type} - Ημερομηνία: {self.date}"

@receiver(post_delete, sender=Shipment)
def delete_shipment_files(sender, instance, **kwargs):
    if instance.attachment:
        if os.path.isfile(instance.attachment.path):
            os.remove(instance.attachment.path)


class Warehouse(models.Model):
    name = models.CharField(max_length=100, db_index=True)  # Added index
    description = models.CharField(max_length=255, blank=True)
    access_groups = models.ManyToManyField(Group, related_name="access_warehouses")

    def __str__(self):
        return f"{self.name}"

class ShipmentItem(models.Model):
    shipment = models.ForeignKey(Shipment, on_delete=models.CASCADE, related_name='shipment_items', db_index=True)  # Added index
    product = models.ForeignKey(Product, on_delete=models.CASCADE, db_index=True)  # Added index
    warehouse = models.ForeignKey(Warehouse, on_delete=models.CASCADE, null=True, db_index=True)  # Added index
    quantity = models.PositiveIntegerField()

    def __str__(self):
        return f"{self.product.name} - Qty: {self.quantity} in {self.shipment}"

    def clean(self):
        """Ensure stock validation before saving the shipment item."""
        if self.shipment.shipment_type == 'OUT':
            stock = Stock.objects.get(product=self.product, warehouse=self.warehouse)
            if stock.quantity < self.quantity:
                raise ValidationError(f'Insufficient stock for {self.product.name} in {self.warehouse.name}. Cannot proceed with the operation.')

    def save(self, *args, **kwargs):
        self.clean()
        super().save(*args, **kwargs)

    def delete(self, *args, skip_validation=False, **kwargs):
        if not skip_validation:
            self.clean()
        super().delete(*args, **kwargs)

@receiver(post_save, sender=ShipmentItem)
def adjust_stock_on_save(sender, instance, created, **kwargs):
    adjust_stock(instance, created=True)

@receiver(post_delete, sender=ShipmentItem)
def adjust_stock_on_delete(sender, instance, **kwargs):
    adjust_stock(instance, created=False)

def adjust_stock(instance, created):
    with transaction.atomic():
        stock, _ = Stock.objects.get_or_create(
            product=instance.product,
            warehouse=instance.warehouse,
            defaults={'quantity': 0}
        )

        # Determine the adjustment direction based on the shipment type
        if instance.shipment.shipment_type == 'IN':
            adjustment = instance.quantity if created else -instance.quantity
        elif instance.shipment.shipment_type == 'OUT':
            adjustment = -instance.quantity if created else instance.quantity

        # Apply the adjustment
        stock.quantity += adjustment

        # Prevent stock from going negative for 'OUT' shipments
        if stock.quantity < 0:
            raise ValidationError(f'Insufficient stock for {instance.product.name} in {instance.warehouse.name}. Cannot proceed with the operation.')

        stock.save()

class Stock(models.Model):
    product = models.ForeignKey(Product, on_delete=models.CASCADE, related_name='stocks', db_index=True)  # Added index
    warehouse = models.ForeignKey(Warehouse, on_delete=models.CASCADE, related_name='stocks', db_index=True)  # Added index
    quantity = models.PositiveIntegerField(default=0)

    class Meta:
        unique_together = ('product', 'warehouse')

    def __str__(self):
        return f"{self.product.name} in {self.warehouse.name} - Qty: {self.quantity}"

hud_django_v1.0/template_django/DjangoHUDApp/forms.py
# forms.py
from django import forms
from .models import Product, Shipment, ShipmentItem, Warehouse
from django.forms import inlineformset_factory
from django.contrib.auth.models import Group
from .models import Product, ProductCategory, ProductUsage
from django.utils import timezone

class LoginForm(forms.Form):
    username = forms.CharField(
        max_length=100,
        widget=forms.TextInput(attrs={'class': 'form-control form-control-lg bg-inverse bg-opacity-5', 'placeholder': 'Username'})
    )
    password = forms.CharField(
        widget=forms.PasswordInput(attrs={'class': 'form-control form-control-lg bg-inverse bg-opacity-5', 'placeholder': 'Password'})
    )

class ProductForm(forms.ModelForm):
    name = forms.CharField(widget=forms.TextInput(attrs={'class': 'form-control', 'placeholder': 'Όνομα Υλικού'}))
    batch_number = forms.CharField(widget=forms.TextInput(attrs={'class': 'form-control', 'placeholder': 'Αριθμός Μερίδας Υλικού'}), required=False)
    description = forms.CharField(widget=forms.Textarea(attrs={'class': 'form-control', 'rows': 10}), required=False)
    category = forms.ModelChoiceField(queryset=ProductCategory.objects.all(), required=False, widget=forms.Select(attrs={'class': 'form-select'}))
    usage = forms.ModelChoiceField(queryset=ProductUsage.objects.all(), required=False, widget=forms.Select(attrs={'class': 'form-select'}))
    unit_of_measurement = forms.ChoiceField(choices=Product.MEASUREMENT_TYPES, widget=forms.Select(attrs={'class': 'form-select'}), required=False)
    image = forms.ImageField(required=False, widget=forms.FileInput(attrs={'class': 'form-control'}))  # Adding the image field

    class Meta:
        model = Product
        fields = ['name', 'batch_number', 'category', 'usage', 'description', 'unit_of_measurement', 'image']
        labels = {
            'name': 'Όνομα Προϊόντος',
            'batch_number': 'Αριθμός Μερίδας',
            'category': 'Κατηγορία Προϊόντος',
            'usage': 'Χρήση Προϊόντος',
            'description': 'Περιγραφή',
            'unit_of_measurement': 'Μονάδα Μέτρησης',
            'image': 'Εικόνα Προϊόντος'
        }

    def __init__(self, *args, **kwargs):
        user = kwargs.pop('user', None)
        super().__init__(*args, **kwargs)
        if user:
            user_groups = user.groups.all()
            self.fields['owners'].queryset = Group.objects.filter(user__in=user_groups).distinct()

class ShipmentForm(forms.ModelForm):
    class Meta:
        model = Shipment
        fields = ['shipment_type', 'recipient', 'signatory', 'date', 'order_number', 'notes', 'attachment']
        widgets = {
            'date': forms.DateTimeInput(attrs={'class': 'form-control', 'placeholder': 'Select a date and time', 'type': 'text'}),
            'shipment_type': forms.Select(attrs={'class': 'form-select', 'id': 'shipment_type_id'}),
            'recipient': forms.Select(attrs={'class': 'form-select', 'id': 'recipient_id'}),
            'signatory': forms.TextInput(attrs={'class': 'form-control', 'id': 'signatory_id'}),
            'order_number': forms.TextInput(attrs={'class': 'form-control', 'id': 'order_number_id'}),
            'notes': forms.Textarea(attrs={'class': 'form-control', 'rows': 3}),
            'attachment': forms.FileInput(attrs={'class': 'form-control'})  # Add this line for file input
        }
        labels = {
            'shipment_type': 'Τύπος Αποστολής',  # Custom title for shipment_type
            'recipient': 'Παραλήπτης (OUT) / Αποστολέας (IN)',  # Custom title for recipient
            'signatory': 'Υπογεγραμμένος',  # Custom title for recipient
            'date': 'Ημερομηνία',  # Custom title for date
            'order_number': 'Αριθμός Διαταγής',
            'notes': 'Σημειώσεις',  # Custom title for notes
            'attachment': 'Συνημμένο'  # Custom title for attachment
        }

    date = forms.DateField(input_formats=['%d-%m-%Y'], widget=forms.DateInput(attrs={
        'class': 'form-control', 'placeholder': 'Select a date', 'type': 'text', 'autocomplete': 'off'
    }))

    def __init__(self, *args, **kwargs):
        super(ShipmentForm, self).__init__(*args, **kwargs)
        self.fields['date'].initial = timezone.now().strftime('%d-%m-%Y')

class ShipmentItemForm(forms.ModelForm):
    class Meta:
        model = ShipmentItem
        fields = ['product', 'warehouse', 'quantity']
        labels = {
            'product': 'Προϊόντος',  # Custom title for shipment_type
            'warehouse': 'Αποθήκη',  # Custom title for recipient
            'quantity': 'Ποσότητα'  # Custom title for date
        }

    def __init__(self, *args, **kwargs):
        user = kwargs.pop('user', None)  # Extract the user from the keyword arguments
        super().__init__(*args, **kwargs)
        if user:
            if user.is_superuser:
                self.fields['product'].queryset = Product.objects.all().order_by('name')
                self.fields['warehouse'].queryset = Warehouse.objects.all()
            else:
                user_groups = user.groups.all()
                self.fields['product'].queryset = Product.objects.filter(owners__in=user_groups).distinct().order_by('name')
                self.fields['warehouse'].queryset = Warehouse.objects.filter(access_groups__in=user_groups).distinct()
        self.fields['product'].widget.attrs.update({'class': 'form-select mb-2'})
        self.fields['warehouse'].widget.attrs.update({'class': 'form-select'})
        self.fields['quantity'].widget.attrs.update({'class': 'form-control', 'placeholder': 'Ποσότητα'})

class ShipmentItemFormSetWithUser(forms.BaseInlineFormSet):
    def __init__(self, *args, **kwargs):
        self.user = kwargs.pop('user', None)  # Extract the user from the keyword arguments
        super().__init__(*args, **kwargs)
        for form in self.forms:
            if self.user.is_superuser:
                form.fields['product'].queryset = Product.objects.all().order_by('name')
                form.fields['warehouse'].queryset = Warehouse.objects.all()
            else:
                user_groups = self.user.groups.all()
                form.fields['product'].queryset = Product.objects.filter(owners__in=user_groups).distinct().order_by('name')
                form.fields['warehouse'].queryset = Warehouse.objects.filter(access_groups__in=user_groups).distinct()

    def clean(self):
        super().clean()
        if any(self.errors):
            return
        if not any(form.cleaned_data and not form.cleaned_data.get('DELETE', False) for form in self.forms):
            raise forms.ValidationError('You must add at least one shipment item.')

ShipmentItemFormSet = inlineformset_factory(
    Shipment,
    ShipmentItem,
    form=ShipmentItemForm,  # Use the customized form
    formset=ShipmentItemFormSetWithUser,
    fields=('product', 'warehouse', 'quantity'),
    extra=1,
    can_delete=True
)

hud_django_v1.0/template_django/DjangoHUDApp/templates/pages/all-orders.html
{% extends 'base.html' %}

{% load static %}
{% load filters_tags %}

{% block title %}Διακινήσεις{% endblock %}

{% block content %}
    <div class="d-flex align-items-center mb-3">
        <div>
            <h1 class="page-header mb-0">Διακινήσεις</h1>
        </div>
        <div class="ms-auto">
            <a href="add-shipment" class="btn btn-outline-theme"><i class="fa fa-plus-circle fa-fw me-1"></i> Δημιουργία Διακίνησης</a>
        </div>
    </div>
    {% render_shipment_filter_form filter %}

    <div class="card">
        <div class="tab-content p-4">
            <div class="tab-pane fade show active" id="allTab">
                <div class="table-responsive">
                    <table class="table table-hover text-nowrap">
                        <thead>
                            <tr>
                                <th class="border-top-0 pt-0 pb-2"></th>
                                <th class="border-top-0 pt-0 pb-2">Αρ.</th>
                                <th class="border-top-0 pt-0 pb-2">Ημερομηνία</th>
                                <th class="border-top-0 pt-0 pb-2">Παραλήπτης / Αποστολέας</th>
                                <th class="border-top-0 pt-0 pb-2">Τύπος Αποστολής</th>
                                <th class="border-top-0 pt-0 pb-2">Προιόντα</th>
                                <th class="border-top-0 pt-0 pb-2">Δημιουργός</th>
                                <th class="border-top-0 pt-0 pb-2">Σχόλια</th>
                                <th class="border-top-0 pt-0 pb-2">Διαγραφή</th>
                            </tr>
                        </thead>
                        <tbody>
                            {% for shipment in shipments %}
                            <tr>
                                <td class="w-10px align-middle">
                                    <a href="{% url 'DjangoHUDApp:order_print' shipment_id=shipment.id %}" class="btn" target="_blank">
                                        <i class="bi bi-printer"></i>
                                    </a>
                                </td>
                                <td class="align-middle">
                                    <a href="{% url 'DjangoHUDApp:pageOrderDetails' shipment.id %}">
                                        #{{ shipment.id }}
                                    </a>
                                </td>
                                <td class="align-middle">{{ shipment.date|date:"d-m-Y" }}</td>
                                <td>{{ shipment.recipient|default:"-" }}</td>
                                <td class="py-1 align-middle">
                                {% if shipment.shipment_type == 'IN' %}
                                    <span class="badge border border-success text-success px-2 pt-5px pb-5px rounded fs-12px d-inline-flex align-items-center"><i class="fa fa-circle fs-9px fa-fw me-5px"></i> IN</span>
                                {% elif shipment.shipment_type == 'OUT' %}
                                    <span class="badge border border-warning text-warning px-2 pt-5px pb-5px rounded fs-12px d-inline-flex align-items-center"><i class="fa fa-circle fs-9px fa-fw me-5px"></i> OUT</span>
                                {% endif %}
                                    </td>
                                <td class="align-middle">
                                    <ul class="list-unstyled mb-0" style="font-size: smaller;">
                                        {% for item in shipment.shipment_items.all %}
                                            <li>{{ item.product.name }}</li>
                                        {% endfor %}
                                    </ul>
                                </td>                            
                                <td class="align-middle">{{ shipment.user.username }}</td>
                                <td class="align-middle">{{shipment.notes}}</td>
                                <td class="align-middle">
                                    <form method="post" action="{% url 'DjangoHUDApp:delete_shipment' shipment.id %}" style="display:inline;" onsubmit="return confirmDelete();">
                                        {% csrf_token %}
                                        <button type="submit" class="btn btn-danger btn-sm"><i class="fa fa-times"></i></button>
                                    </form>
                                </td>
                            </tr>
                            {% endfor %}
                        </tbody>
                    </table>
                </div>
                
                <div class="d-md-flex align-items-center">
                    <div class="me-md-auto text-md-left text-center mb-2 mb-md-0">
                        Showing {{ shipments.start_index }} to {{ shipments.end_index }} of {{ shipments.paginator.count }} entries
                    </div>
                    <ul class="pagination mb-0 justify-content-center">
                        {% if shipments.has_previous %}
                        <li class="page-item"><a class="page-link" href="?page=1">First</a></li>
                        <li class="page-item"><a class="page-link" href="?page={{ shipments.previous_page_number }}">Previous</a></li>
                        {% else %}
                        <li class="page-item disabled"><a class="page-link">First</a></li>
                        <li class="page-item disabled"><a class="page-link">Previous</a></li>
                        {% endif %}
                        {% for num in shipments.paginator.page_range %}
                        {% if shipments.number == num %}
                        <li class="page-item active"><a class="page-link" href="?page={{ num }}">{{ num }}</a></li>
                        {% elif num > shipments.number|add:'-3' and num < shipments.number|add:'3' %}
                        <li class="page-item"><a class="page-link" href="?page={{ num }}">{{ num }}</a></li>
                        {% endif %}
                        {% endfor %}
                        {% if shipments.has_next %}
                        <li class="page-item"><a class="page-link" href="?page={{ shipments.next_page_number }}">Next</a></li>
                        <li class="page-item"><a class="page-link" href="?page={{ shipments.paginator.num_pages }}">Last</a></li>
                        {% else %}
                        <li class="page-item disabled"><a class="page-link">Next</a></li>
                        <li class="page-item disabled"><a class="page-link">Last</a></li>
                        {% endif %}
                    </ul>
                </div>
            </div>
        </div>
        <div class="card-arrow">
            <div class="card-arrow-top-left"></div>
            <div the="card-arrow-top-right"></div>
            <div the="card-arrow-bottom-left"></div>
            <div the="card-arrow-bottom-right"></div>
        </div>
    </div>

    <script>
        function confirmDelete() {
            return confirm("ΠΡΟΣΟΧΗ! Αυτή η ενέργεια θα διαγράψει την αποστολή και θα αλλάξουν οι ποσότητες των αποθηκών");
        }
    </script>
{% endblock %}

hud_django_v1.0/template_django/DjangoHUDApp/templates/pages/all-products.html
{% extends 'base.html' %}
{% load static %}
{% load filters_tags %}

{% block title %}Products{% endblock %}

{% block css %}
    <link href="{% static 'css/lightbox.css' %}" rel="stylesheet">
{% endblock %}

{% block js %}
    <script src="{% static 'js/lightbox.js' %}"></script>
{% endblock %}

{% block content %}
    <div class="d-flex align-items-center mb-3">
        <div>
            <h1 class="page-header mb-0">Λίστα Προιόντων</h1>
        </div>
        
        <div class="ms-auto">
            <a href="add-product" class="btn btn-outline-theme"><i class="fa fa-plus-circle fa-fw me-1"></i> Νέο Προιόν</a>
        </div>
    </div>
    <!-- Include the filter form -->
    {% render_product_filter_form filter %}
    <div class="card">
        <div class="tab-content p-4">
            <div class="tab-pane fade show active" id="allTab">

                <!-- BEGIN table -->
                <div class="table-responsive">
                    <table class="table table-hover text-nowrap">
                        <thead>
                            <tr>
                                <th class="pt-0 pb-2">Προιόν</th>
                                <th class="pt-0 pb-2">Απόθεμα</th>
                                <th class="pt-0 pb-2">Κατηγορία</th>
                                <th class="pt-0 pb-2">Χρήση</th>
                                <th class="border-top-0 pt-0 pb-2">Διαγραφή</th>
                            </tr>
                        </thead>
                        <tbody>
                            {% for product in products %}
                                <tr>
                                    <td>
                                        <div class="d-flex align-items-center">
                                            <div class="w-50px h-50px bg-inverse bg-opacity-25 d-flex align-items-center justify-content-center">
                                                {% if product.image %}
                                                    <a href="{{ product.image.url }}" data-lightbox="product-{{ product.id }}" data-title="{{ product.name }}">
                                                        <img alt="{{ product.name }}" class="mw-100 mh-100" src="{{ product.image.url }}">
                                                    </a>
                                                {% else %}
                                                    <img alt="" class="mw-100 mh-100" src="{% static 'img/default-image.svg' %}">
                                                {% endif %}
                                            </div>
                                            <div class="ms-3">
                                                <a href="{% url 'DjangoHUDApp:pageProductDetails' product.id %}" class="text-inverse text-opacity-75 text-decoration-none">{{ product.name }}</a>
                                            </div>
                                        </div>
                                    </td>
                                    <td class="align-middle">{{ product.total_stock }}</td> <!-- Display total stock -->
                                    <td class="align-middle">{{ product.category }}</td>
                                    <td class="align-middle">{{ product.usage }}</td>
                                    <td class="align-middle">
                                        <form method="post" action="{% url 'DjangoHUDApp:delete_product' product.id %}" style="display:inline;">
                                            {% csrf_token %}
                                            <button type="submit" class="btn btn-danger btn-sm"><i class="fa fa-times"></i></button>
                                        </form>
                                    </td>
                                </tr>
                            {% empty %}
                                <tr>
                                    <td colspan="5" class="text-center">No products found.</td>
                                </tr>
                            {% endfor %}
                        </tbody>
                    </table>
                </div>
                <!-- END table -->
                
                <div class="d-md-flex align-items-center">
                    <div class="me-md-auto text-md-left text-center mb-2 mb-md-0">
                        Showing {{ products.start_index }} to {{ products.end_index }} of {{ products.paginator.count }} entries
                    </div>
                    <ul class="pagination mb-0 justify-content-center">
                        {% if products.has_previous %}
                            <li class="page-item"><a class="page-link" href="?page=1">Πρώτη</a></li>
                            <li class="page-item"><a class="page-link" href="?page={{ products.previous_page_number }}">Προηγούμενη</a></li>
                        {% else %}
                            <li class="page-item disabled"><a class="page-link">Πρώτη Σελίδα</a></li>
                            <li class="page-item disabled"><a class="page-link">Προηγούμενη</a></li>
                        {% endif %}
                        
                        {% for num in products.paginator.page_range %}
                            {% if products.number == num %}
                                <li class="page-item active"><a class="page-link" href="?page={{ num }}">{{ num }}</a></li>
                            {% elif num > products.number|add:'-3' and num < products.number|add:'3' %}
                                <li class="page-item"><a class="page-link" href="?page={{ num }}">{{ num }}</a></li>
                            {% endif %}
                        {% endfor %}
                        
                        {% if products.has_next %}
                            <li class="page-item"><a class="page-link" href="?page={{ products.next_page_number }}">Επόμενη</a></li>
                            <li class="page-item"><a class="page-link" href="?page={{ products.paginator.num_pages }}">Τελευταία</a></li>
                        {% else %}
                            <li class="page-item disabled"><a class="page-link">Επόμενη</a></li>
                            <li class="page-item disabled"><a class="page-link">Τελευταία</a></li>
                        {% endif %}
                    </ul>
                </div>
            </div>
        </div>
        <div class="card-arrow">
            <div class="card-arrow-top-left"></div>
            <div class="card-arrow-top-right"></div>
            <div class="card-arrow-bottom-left"></div>
            <div class="card-arrow-bottom-right"></div>
        </div>
    </div>
{% endblock %}