hud_django_v1.0/template_django/DjangoHUD/urls.py
from django.contrib import admin
from django.urls import include, path
from django.conf.urls.static import static
from django.conf import settings

urlpatterns = [
    path('', include('DjangoHUDApp.urls')),
    path('admin/', admin.site.urls),
] 

handler404 = 'DjangoHUDApp.views.handler404'

if settings.DEBUG:
    urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)
else:
    urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

hud_django_v1.0/template_django/DjangoHUDApp/urls.py
from django.urls import path
from . import views

app_name = 'DjangoHUDApp'
urlpatterns = [
    # in use
    
    #general pages
    path('', views.pageLogin, name='pageLogin'),
    path('index', views.index, name='index'),
    path('404/', views.error404, name='error404'),
    path('page/error', views.pageError, name='pageError'),  
    path('logout/', views.logout_view, name='logout'),

    #product pages
    path('all-products', views.pageProduct, name='pageProduct'),
    path('add-product', views.add_product, name='add_product'),
    path('product-details/<int:product_id>/', views.product_details, name='pageProductDetails'),
    path('delete-product/<int:product_id>/', views.delete_product, name='delete_product'),

    #order pages
    path('add-shipment', views.add_shipment, name='add_shipment'),
    path('order', views.pageOrder, name='pageOrder'),
    path('order-details/<int:shipment_id>/', views.pageOrderDetails, name='pageOrderDetails'),
    path('order-details/<int:shipment_id>/print/', views.order_print, name='order_print'),
    path('delete-shipment/<int:shipment_id>/', views.delete_shipment, name='delete_shipment'),
    
    #warehouse pages
    path('warehouse', views.pageWarehouse, name='pageWarehouse'),
    path('stock-per-warehouse/<str:warehouse_name>/', views.stockPerWarehouse, name='pageStockPerWarehouse'),

    #stock pages
    path('stock', views.pageDataManagement, name='pageDataManagement'),

    #recipient pages
    path('recipient', views.pageRecipient, name='pageRecipient'),

    # not in use
    path('analytics/', views.analytics, name='  '),
    path('chart/js/', views.chartJs, name='chartJs'),
    path('chart/apex/', views.chartApex, name='chartApex'),
]

handler404 = 'DjangoHUDApp.views.handler404'

hud_django_v1.0/template_django/DjangoHUDApp/views.py
from django.shortcuts import get_object_or_404, render, redirect
from django.http import HttpResponse
from django.contrib.auth import authenticate, login, logout
from .forms import LoginForm
from django.http import HttpResponse  # Add this import
from .forms import ProductForm, ShipmentForm, ShipmentItemFormSet
from .models import Product, Shipment, Warehouse, Recipient, ShipmentItem, Stock, ProductCategory, ProductUsage  
from django.core.paginator import Paginator
from django.contrib.auth.decorators import login_required
from django.db.models import Sum,F, Q
from django.contrib.auth.decorators import login_required
from .filters import ProductFilter, ShipmentFilter, RecipientFilter, StockFilter
from django.utils.dateparse import parse_date
from django.utils import timezone
from django.contrib import messages
import pandas as pd
from django.core.files.storage import FileSystemStorage
from django.db import transaction
from django.core.exceptions import ValidationError
from .models import ProductCategory, ProductUsage
from django.urls import reverse
from django.db.models import Q
from datetime import timedelta
from django.db.models import Sum, Max


# Function for loging a user 
def pageLogin(request):
    if request.method == 'GET':
        form = LoginForm()
    else:  # POST request
        form = LoginForm(request.POST)
        if form.is_valid():
            username = form.cleaned_data['username']
            password = form.cleaned_data['password']
            user = authenticate(request, username=username, password=password)
            if user is not None:
                login(request, user)
                return redirect('DjangoHUDApp:index')  # Make sure 'dashboard' is a valid named route in your urls.py
            else:
                # For debugging: Return a simple response indicating failure
                return HttpResponse("Invalid login attempt", status=401)
        else:
            # For debugging: Indicate form is not valid
            return HttpResponse("Form is not valid", status=400)
    
    context = {
        "form": form,
        "appSidebarHide": 1,
        "appHeaderHide": 1,
        "appContentClass": 'p-0'
    }
    return render(request, "pages/login.html", context)

def logout_view(request):
     logout(request)
     return redirect('DjangoHUDApp:pageLogin')

# Function for creating a product 
@login_required
def add_product(request):
    if request.method == 'POST':
        form = ProductForm(request.POST, request.FILES)
        if form.is_valid():
            product = form.save(commit=False)
            product.save()
            product.owners.set(request.user.groups.all())  # Assign the product to the user's groups
            product.save()
            return redirect('DjangoHUDApp:pageProduct')  # Redirect to an appropriate page after saving
        else:
            return render(request, 'pages/add_product.html', {
                'form': form,
                'product_category_choices': Product.PRODUCT_CATEGORY,
                'product_usage_choices': Product.PRODUCT_USAGE,
                'unit_of_measurement_choices': Product.MEASUREMENT_TYPES,
            })
    else:
        form = ProductForm()
        context = {
            'form': form,
            'product_category_choices': ProductCategory.objects.all(),
            'product_usage_choices': ProductUsage.objects.all(),
            'unit_of_measurement_choices': Product.MEASUREMENT_TYPES,
        }
        return render(request, 'pages/add_product.html', context)
    
    
@login_required
def pageProduct(request):
    user_groups = request.user.groups.all()
    if request.user.is_superuser:
        products_list = Product.objects.annotate(total_stock=Sum('stocks__quantity'))
    else:
        products_list = Product.objects.filter(owners__in=user_groups).annotate(total_stock=Sum('stocks__quantity')).distinct()

    product_filter = ProductFilter(request.GET, queryset=products_list)
    products_list = product_filter.qs

    paginator = Paginator(products_list, 10)  # Show 10 products per page
    page_number = request.GET.get('page')
    products = paginator.get_page(page_number)

    context = {'products': products, 'filter': product_filter}
    return render(request, "pages/all-products.html", context)


@login_required
def delete_product(request, product_id):
    product = get_object_or_404(Product, id=product_id)
    product.delete()
    messages.success(request, 'Shipment deleted successfully.')
    return redirect(reverse('DjangoHUDApp:pageProduct'))


# Function for individual product details
@login_required
def product_details(request, product_id):
    product = get_object_or_404(Product, pk=product_id)
    
    if request.method == 'POST':
        form = ProductForm(request.POST, request.FILES, instance=product)
        if form.is_valid():
            form.save()
            return redirect('DjangoHUDApp:pageProduct')  # Redirect to an appropriate page after updating
    else:
        form = ProductForm(instance=product)
    
    context = {
        'form': form,
        'product': product,
        'product_category_choices': Product.category,
        'product_usage_choices': Product.usage,
        'unit_of_measurement_choices': Product.MEASUREMENT_TYPES,
    }
    return render(request, 'pages/product-details.html', context)


@login_required
def add_shipment(request):
    if request.method == 'POST':
        form = ShipmentForm(request.POST, request.FILES)
        formset = ShipmentItemFormSet(request.POST, prefix='shipmentitem', user=request.user)

        if form.is_valid():
            if formset.is_valid():
                if any(item.cleaned_data and not item.cleaned_data.get('DELETE', False) for item in formset):
                    try:
                        with transaction.atomic():
                            shipment = form.save(commit=False)
                            shipment.user = request.user
                            shipment.save()

                            formset.instance = shipment
                            formset.save()

                            return redirect('DjangoHUDApp:pageOrder')
                    except ValidationError as e:
                        form.add_error(None, e)
                else:
                    formset._non_form_errors = formset.error_class(["You must add at least one shipment item."])
            else:
                form.add_error(None, "Please correct the errors below.")
        else:
            print(form.errors)
            print(formset.errors)
    else:
        initial_date = timezone.now().strftime('%d-%m-%Y')
        form = ShipmentForm(initial={'date': initial_date})
        formset = ShipmentItemFormSet(prefix='shipmentitem', user=request.user)

    return render(request, 'pages/add_order.html', {'form': form, 'formset': formset})

@login_required
def delete_shipment(request, shipment_id):
    shipment = get_object_or_404(Shipment, id=shipment_id)
    shipment.delete()
    messages.success(request, 'Shipment deleted successfully.')
    return redirect(reverse('DjangoHUDApp:pageOrder'))

@login_required
def pageOrder(request):
    user = request.user

    # Admin users see all shipments
    if user.is_superuser:
        shipments_list = Shipment.objects.all()
    else:
        # Filter shipments by the groups of the user
        user_groups = user.groups.values_list('name', flat=True)
        if 'ΔΙΔΕΣ' in user_groups:
            # Users in ΔΙΔΕΣ see shipments from all users in this group
            shipments_list = Shipment.objects.filter(user__groups__name='ΔΙΔΕΣ')
        elif 'ΔΟΡΥΦΟΡΙΚΑ' in user_groups:
            # Users in ΔΟΡΥΦΟΡΙΚΑ only see their own shipments
            shipments_list = Shipment.objects.filter(user=user)
        else:
            # Default to no shipments if no specific group is found
            shipments_list = Shipment.objects.none()

    # Apply the filter
    shipments_filter = ShipmentFilter(request.GET, queryset=shipments_list)
    shipments_list = shipments_filter.qs

    # Sort by most recent date
    shipments_list = shipments_list.order_by('-date')

    # Paginate the results
    paginator = Paginator(shipments_list, 10)  # Show 10 shipments per page
    page_number = request.GET.get('page')
    shipments = paginator.get_page(page_number)

    context = {
        'shipments': shipments,
        'filter': shipments_filter,
    }
    return render(request, "pages/all-orders.html", context)

    
@login_required
def pageWarehouse(request):
    user_groups = request.user.groups.values_list('name', flat=True)

    if request.user.is_superuser or 'Admin' in user_groups:
        warehouses_list = Warehouse.objects.annotate(
            total_stock=Sum('stocks__quantity'),
            last_shipment_date=Max('shipmentitem__shipment__date')
        )
    elif 'ΔΟΡΥΦΟΡΙΚΑ' in user_groups:
        warehouses_list = Warehouse.objects.filter(name="ΔΟΡΥΦΟΡΙΚΑ").annotate(
            total_stock=Sum('stocks__quantity'),
            last_shipment_date=Max('shipmentitem__shipment__date')
        )
    elif 'ΔΙΔΕΣ' in user_groups:
        warehouses_list = Warehouse.objects.filter(name__in=["ΚΕΠΙΚ", "ΤΑΓΜΑ"]).annotate(
            total_stock=Sum('stocks__quantity'),
            last_shipment_date=Max('shipmentitem__shipment__date')
        )
    else:
        warehouses_list = Warehouse.objects.none()

    context = {'warehouses': warehouses_list}
    return render(request, "pages/warehouses.html", context)

@login_required
def pageDataManagement(request):
    if request.method == 'POST' and request.FILES.get('file'):
        file = request.FILES['file']
        file_name = file.name

        if file_name.endswith('.csv'):
            df = pd.read_csv(file)
        elif file_name.endswith('.xlsx'):
            df = pd.read_excel(file, header=0)
        else:
            return HttpResponse("Unsupported file format", status=400)

        # Strip whitespace from column names to avoid KeyError

hud_django_v1.0/template_django/DjangoHUDApp/templates/filters/products-search-form.html
{% load widget_tweaks %}

<form method="get" aclass="form-inline mb-3 d-flex justify-content-center align-items-center">
    <div class="row align-items-center mb-3">
        <!-- Search Input -->
        <div class="col-md-4 mb-2">
            <div class="input-group">
                <input type="text" name="search" class="form-control ps-35px" placeholder="Αναζήτηση Προιόντος"
                       value="{{ filter.data.search }}">
            </div>
        </div>
        <!-- Category Dropdown -->
        <div class="col-md-3 mb-2">
            <div class="dropdown">
                <button class="btn btn-outline-default dropdown-toggle w-100" type="button" data-bs-toggle="dropdown"
                        aria-haspopup="true" aria-expanded="false">Κατηγορία</button>
                <div class="dropdown-menu">
                    {% for choice in filter.form.category.field.choices %}
                <a class="dropdown-item" href="?category={{ choice.0 }}">{{ choice.1 }}</a>

                    {% endfor %}
                </div>
                <input type="hidden" name="category" id="category-input" value="{{ request.GET.category }}">
            </div>
        </div>
        <!-- Usage Dropdown -->
        <div class="col-md-3 mb-2">
            <div class="dropdown">
                <button class="btn btn-outline-default dropdown-toggle w-100" type="button" data-bs-toggle="dropdown"
                        aria-haspopup="true" aria-expanded="false">Χρήση</button>
                <div class="dropdown-menu w-100">
                    {% for choice in filter.form.usage.field.choices  %}
                <a class="dropdown-item" href="?usage={{ choice.0 }}">{{ choice.1 }}</a>

                    {% endfor %}
                </div>
                <input type="hidden" name="usage" id="usage-input" value="{{ request.GET.usage }}">
            </div>
        </div>
        <!-- Submit Button -->
        <div class="col-md-1 mb-2">
            <button type="submit" class="btn btn-theme w-100"><i class="fa fa-search"></i></button>
        </div>
        <!-- Clear Filters Button -->
        <div class="col-md-1 mb-2">
            <a href="{% url 'DjangoHUDApp:pageOrder' %}" class="btn btn-outline-secondary w-100">
                <i class="fa fa-times"></i>
            </a>
        </div>
    </div>
</form>

hud_django_v1.0/template_django/DjangoHUDApp/templates/filters/recipients-search-form.html
{% load widget_tweaks %}
<form method="get" class="form-inline mb-3 d-flex justify-content-center align-items-center">
    <div class="row align-items-center mb-3 w-100">
        <!-- Search Input -->
        <div class="col-md-6 mb-2">
            <div class="input-group">
                <input type="text" name="search" class="form-control ps-35px" placeholder="Αναζήτηση Παραλήπτη" value="{{ request.GET.search }}">
            </div>
        </div>
        <div class="col-md-1 mb-2">
            <button type="submit" class="btn btn-theme w-100"><i class="fa fa-search"></i></button>
        </div>
        <div class="col-md-1 mb-2">
            <a href="{% url 'DjangoHUDApp:pageRecipient' %}" class="btn btn-outline-secondary w-100">
                <i class="fa fa-times"></i>
            </a>
        </div>
    </div>
</form>

hud_django_v1.0/template_django/DjangoHUDApp/templates/filters/shipments-search-form.html
{% load widget_tweaks %}

<form method="get" class="form-inline mb-3 d-flex justify-content-center align-items-center">
    <div class="row align-items-center mb-3 w-100">
        <!-- Search Input -->
        <div class="col-md-2 mb-2">
            <div class="input-group">
                <input type="text" name="order_number" class="form-control ps-35px" placeholder="Αριθμός Αποστολής" value="{{ request.GET.order_number }}">
            </div>
        </div>
        <!-- Shipment Type Dropdown -->
        <div class="col-md-2 mb-2">
            <div class="dropdown">
                <button class="btn btn-outline-default dropdown-toggle w-100" type="button" data-bs-toggle="dropdown"
                        aria-haspopup="true" aria-expanded="false">Τύπος Διακίνησης</button>
                <div class="dropdown-menu">
                    {% for choice in filter.form.shipment_type.field.choices %}
                        <a class="dropdown-item" href="?shipment_type={{ choice.0 }}{% if request.GET.recipient %}&recipient={{ request.GET.recipient }}{% endif %}{% if request.GET.start_date %}&start_date={{ request.GET.start_date }}{% endif %}{% if request.GET.end_date %}&end_date={{ request.GET.end_date }}{% endif %}">{{ choice.1 }}</a>
                    {% endfor %}
                </div>
                <input type="hidden" name="shipment_type" id="shipment_type-input" value="{{ request.GET.shipment_type }}">
            </div>
        </div>
        <!-- Recipient Dropdown -->
        <div class="col-md-2 mb-2">
            <div class="dropdown">
                <button class="btn btn-outline-default dropdown-toggle w-100" type="button" data-bs-toggle="dropdown"
                        aria-haspopup="true" aria-expanded="false">Παραλήπτης</button>
                <div class="dropdown-menu w-100">
                   {% for choice in filter.form.recipient.field.choices %}
                        <a class="dropdown-item" href="?recipient={{ choice.0 }}{% if request.GET.shipment_type %}&shipment_type={{ request.GET.shipment_type }}{% endif %}{% if request.GET.start_date %}&start_date={{ request.GET.start_date }}{% endif %}{% if request.GET.end_date %}&end_date={{ request.GET.end_date }}{% endif %}">{{ choice.1 }}</a>
                    {% endfor %}
                </div>
                <input type="hidden" name="recipient" id="recipient-input" value="{{ request.GET.recipient }}">
            </div>
        </div>
        <!-- Start Date -->
        <div class="col-md-2 mb-2">
            <div class="input-group">
                <input type="date" name="start_date" class="form-control" placeholder="Από"
                       value="{{ request.GET.start_date }}">
            </div>
        </div>
        <!-- End Date -->
        <div class="col-md-2 mb-2">
            <div class="input-group">
                <input type="date" name="end_date" class="form-control" placeholder="Έως"
                       value="{{ request.GET.end_date }}">
            </div>
        </div>
        <!-- Submit Button -->
        <div class="col-md-1 mb-2">
            <button type="submit" class="btn btn-theme w-100"><i class="fa fa-search"></i></button>
        </div>
        <!-- Clear Filters Button -->
        <div class="col-md-1 mb-2">
            <a href="{% url 'DjangoHUDApp:pageOrder' %}" class="btn btn-outline-secondary w-100">
                <i class="fa fa-times"></i>
            </a>
        </div>
    </div>
</form>

hud_django_v1.0/template_django/DjangoHUDApp/templates/filters/stock-search-form.html
{% load widget_tweaks %}

<form method="get" class="form-inline mb-3 d-flex justify-content-center align-items-center">
    <div class="row align-items-center mb-3 w-100">
        <!-- Search Input -->
        <div class="col-md-4 mb-2">
            <div class="input-group">
                <input type="text" name="search" class="form-control ps-35px" placeholder="Αναζήτηση Προιόντος"
                       value="{{ request.GET.search }}">
            </div>
        </div>
        <!-- Category Dropdown -->
        <div class="col-md-3 mb-2">
            <div class="dropdown">
                <button class="btn btn-outline-default dropdown-toggle w-100" type="button" data-bs-toggle="dropdown"
                        aria-haspopup="true" aria-expanded="false">Κατηγορία</button>
                <div class="dropdown-menu w-100">
                    {% for choice in filter.form.fields.product__category.queryset %}
                        <a class="dropdown-item" href="?search={{ request.GET.search }}&category={{ choice.id }}&usage={{ request.GET.usage }}">{{ choice.name }}</a>
                    {% endfor %}
                </div>
                <input type="hidden" name="category" id="category-input" value="{{ request.GET.category }}">
            </div>
        </div>
        <!-- Usage Dropdown -->
        <div class="col-md-3 mb-2">
            <div class="dropdown">
                <button class="btn btn-outline-default dropdown-toggle w-100" type="button" data-bs-toggle="dropdown"
                        aria-haspopup="true" aria-expanded="false">Χρήση</button>
                <div class="dropdown-menu w-100">
                    {% for choice in filter.form.fields.product__usage.queryset %}
                        <a class="dropdown-item" href="?search={{ request.GET.search }}&category={{ request.GET.category }}&usage={{ choice.id }}">{{ choice.name }}</a>
                    {% endfor %}
                </div>
                <input type="hidden" name="usage" id="usage-input" value="{{ request.GET.usage }}">
            </div>
        </div>
        <!-- Submit Button -->
        <div class="col-md-1 mb-2">
            <button type="submit" class="btn btn-theme w-100"><i class="fa fa-search"></i></button>
        </div>
        <!-- Clear Filters Button -->
        <div class="col-md-1 mb-2">
            <a href="{% url 'DjangoHUDApp:pageOrder' %}" class="btn btn-outline-secondary w-100">
                <i class="fa fa-times"></i>
            </a>
        </div>
    </div>
</form>